### ISSUE TITLE
Update navigation for documentation site

### ISSUE THREAD

**Issue by nick-verida** [verida/documentation#104]
The following changes are needed
* Update the footer to be the same as at https://verida.io
* Fix the "Terms & Conditions" link to go to https://www.verida.io/terms-and-conditions
* In the top (header) menu to be: 
  * (Left aligned): Verida Logo [Documentation](https://developers.verida.io/docs/intro) [API](https://developers.verida.io/docs/api/verida-js) [Tutorial](https://developers.verida.io/docs/tutorial/introduction) [Demos](https://developers.verida.io/docs/demos)
  * (Right aligned): [Verida Homepage](https://www.verida.io/) [Github](https://github.com/verida) Search 
* Fix the copyright link and text in the footer (to be the same as https://verida.io)

**Comment by cmcWebCode40** [comment]
@nick-verida 

> In the top (header) menu to be:
(Left aligned): Verida Logo [Documentation](https://developers.verida.io/docs/intro) [API](https://developers.verida.io/docs/api/verida-js) [Tutorial](https://developers.verida.io/docs/tutorial/introduction) [Demos](https://developers.verida.io/docs/demos)
(Right aligned): [Verida Homepage](https://www.verida.io/) [Github](https://github.com/verida) Search

Please I don't seem to understand exactly what I should implement here because the :

- Verida Logo is left-aligned on the page 
- The search input is right-aligned

its there something i need to do differently ?

**Comment by nick-verida** [comment]
Yeah those should just remain where they are (along with the "Documentation" link which is also remaining).
